AllCops:
  TargetRubyVersion: 3.1.X
  Exclude:
    - app/services/pg_pubsub.rb
    - config/initializers/version.rb
Lint/Debugger:
  Enabled: false
Lint/SuppressedException:
  Exclude:
    - app/controllers/events_controller.rb
Metrics/AbcSize:
  Max: 20
  Exclude:
    - db/migrate/*.rb
    - app/controllers/academic/quizzes/questions_controller.rb
    - app/controllers/academic/quiz_sessions_controller.rb
    - app/controllers/academic/quizzes/sharing_controller.rb
Metrics/BlockLength:
  Exclude:
    - db/schema.rb
    - spec/**/*
    - config/routes.rb
Metrics/MethodLength:
  Max: 20
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*.rb
    - node_modules/**/*.rb
    - config/puma.rb
    - config/initializers/simple_form.rb
    - config/initializers/simple_form_bootstrap.rb
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Lint/FloatComparison:
  Exclude:
    - app/controllers/academic/quiz_sessions_controller.rb
    - app/views/academic/quiz_sessions/show.html.haml
    - app/views/academic/quiz_sessions/_question_with_answers.html.haml
Metrics/PerceivedComplexity:
  Exclude:
    - app/controllers/academic/quiz_sessions_controller.rb
Metrics/ClassLength:
  Exclude:
    - app/controllers/academic/quiz_sessions_controller.rb
